---
driver_plugin: vagrant

provisioner:
  name: chef_zero

platforms:
- name: windows2012r2_cloud
  driver_config:
    box: windows2012r2_cloud
    box_url: https://s3.amazonaws.com/box-cutter-us-east-1-cloudtrail/windows/virtualbox4.3.12/win2012r2-datacenter-chef11.12.8.box
    guest: :windows

suites:
- name: default
  run_list:
    - 'recipe[tk-windows::default]'
  attributes:
