---
driver_plugin: vagrant

provisioner:
  name: chef_zero

transport:
  name: winrm

platforms:
- name: centos-6.5
  transport:
    name: ssh
- name: windows-7
  driver_config:
    box: windows-7
    box_url: https://s3.amazonaws.com/box-cutter-us-east-1-cloudtrail/windows/virtualbox4.3.14/win7x64-enterprise-nocm.box
- name: windows-8.1
  driver_config:
    box: windows-8.1
    box_url: https://s3.amazonaws.com/box-cutter-us-east-1-cloudtrail/windows/virtualbox4.3.14/win81x64-enterprise-nocm.box
- name: windows-2008R2
  driver_config:
    box: windows-2008R2
    box_url: https://s3.amazonaws.com/box-cutter-us-east-1-cloudtrail/windows/virtualbox4.3.14/win2008r2-datacenter-nocm.box
- name: windows-2012R2
  driver_config:
    box: windows-2012R2
    box_url: https://s3.amazonaws.com/box-cutter-us-east-1-cloudtrail/windows/virtualbox4.3.14/win2012-datacenter-nocm.box

suites:
- name: default
  run_list:
    - 'recipe[tk-windows::default]'
  attributes:
