---
driver: 
  name: vagrant
  customize:
    memory: 2048
    cpus: 4

provisioner:
  name: chef_zero

transport:
  name: winrm

platforms:
- name: ubuntu-12.04
  transport:
    name: ssh
- name: centos-6.5
  transport:
    name: ssh
- name: windows-7
  driver_config:
    box: windows-7
    box_url: http://cdn.box-cutter.com/windows/virtualbox4.3.20/i7/eval-win7x64-enterprise-nocm-1.0.3.box
- name: windows-8.1
  driver_config:
    box: windows-8.1
    box_url: http://cdn.box-cutter.com/windows/virtualbox4.3.20/eval-win81x64-enterprise-nocm-1.0.2.box 
- name: windows-2008R2
  transport:
    max_threads: 20
  driver_config:
    box: windows-2008R2
    box_url: http://cdn.box-cutter.com/windows/virtualbox4.3.20/eval-win2008r2-datacenter-nocm-1.0.2.box 
- name: windows-2012R2
  driver_config:
    box: windows-2012R2
    box_url: http://cdn.box-cutter.com/windows/virtualbox4.3.20/eval-win2012r2-datacenter-nocm-1.0.2.box

suites:
- name: win
  run_list:
    - 'recipe[tk-windows::default]'
  attributes:
  excludes:
    - centos-6.5
    - ubuntu-12.04
- name: nix
  run_list:
    - 'recipe[tk-windows::default]'
  attributes:
  excludes:
    - windows-7
    - windows-8.1
    - windows-2008R2
    - windows-2012R2
